### ISSUE TITLE
Select 3 Best Designs

### ISSUE THREAD

**Issue by jakevolkman** [OSU-CS361-W17/group1_project2#6]
After everyone has reviewed the designs posted by everyone, please comment here to identify which 3 you like the best. This is a significant portion of our grade. The 3 that get the most picks will be used to make the merged paper prototype. Thanks.

**Comment by daviandr** [comment]
I like Daniel's last design, although everyone was trying to squeeze two boards on a phone, which would work but it seems like busy screen to me. I tried to make something like a single screen, with one board at a time, and the option to switch between your board and the enemy's board. Because if you are firing, the only reason you would look at your own board is to view how screwed you are. If someone could create a better version of my ideas, I would be all for it.

**Comment by jakevolkman** [comment]
daviandr please choose 3 designs to vote on so that we can tally votes

**Comment by daviandr** [comment]
Daniel's last design, my first two.

**Comment by jakevolkman** [comment]
My vote is for daviandr's 1st and 2nd design and Nick's 2nd design. All three of these boards revolve around one big screen rather than 2, which is less busy. My designs pertained less to visibility and more to thematic elements that would engage a specific type of user (cartoon nerds).

**Comment by daviandr** [comment]
Whatever prototype we choose, let's add the Rick & Morty theme.

**Comment by dmkato** [comment]
David's 2nd design, nick's 1st, and my last one. If we did do one big screen, it could be kinda hard to actually get everything up and running in 2 days, so we might want to stick to the structure that was given?

**Comment by nickywongdong** [comment]
1st: Andrew's 2nd prototype
2nd: Nick's 2nd prototype
3rd: Daniel's 1st prototype

I like having just 1 screen, because I remember that's how battleship was played (everything was on your own board).

**Comment by dmkato** [comment]
I think we're done here
